In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

In [2]:
df=pd.read_excel("homeprices.xlsx")
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      NaN   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [3]:
newdf=df.fillna(0)
newdf

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      0.0   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [7]:
# to find median for filling 0/NaN of bedroom 
df.bedroom.median()

#to keep median as an integer
import math
bedroom_median=math.floor(df.bedroom.median())
bedroom_median

3

In [11]:
#filling median of bedroom in place of 0/NaN and assigning in original dataframe 
df.bedroom=df.bedroom.fillna(bedroom_median)
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      3.0   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [16]:
#to train
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedroom','age']],df.price)

LinearRegression()

In [17]:
#to check coefficients/slope value(m1 m2 m3)
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [18]:
#to check intercept c
reg.intercept_

383724.9999999998

In [19]:
#to predict
reg.predict([[3000,3,40]])

array([444400.])

In [22]:
#to predict
reg.predict([[2500,4,5]])

array([588625.])